import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>{children}</body>
			{/* 포트원 */}
			<Script src="https://cdn.iamport.kr/v1/iamport.js" />

			{/* 페이플 */}
			{/* <Script
				type="text/javascript"
				src="https://code.jquery.com/jquery-3.2.1.min.js"
			></Script>
			<Script src="https://democpay.payple.kr/js/v1/payment.js"></Script>{" "}
			*/}
		</html>
	);
}
